[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install --no-cache-dir -r requirements.txt"
]
